version: '2'
services:
  spec:
    build: .
    working_dir: /opt/amber
    environment:
      REDIS_URL: 'redis://redis:6379'
      AMBER_ENV: test
      CI: "true"
    links:
      - redis
      - db
  db:
    image: postgres:10.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test_app_development
  redis:
    image: redis:4.0.8-alpine

